# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /shares/zitipoolhome/ol233/mb-fpga-VU9P/MandelbulbVU9P/MandelbulbVU9P.srcs/sources_1/ip/mult_35_35_core/mult_35_35_core.xci
# IP: The module: 'mult_35_35_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /shares/zitipoolhome/ol233/mb-fpga-VU9P/MandelbulbVU9P/MandelbulbVU9P.gen/sources_1/ip/mult_35_35_core/mult_35_35_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_35_35_core'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /shares/zitipoolhome/ol233/mb-fpga-VU9P/MandelbulbVU9P/MandelbulbVU9P.srcs/sources_1/ip/mult_35_35_core/mult_35_35_core.xci
# IP: The module: 'mult_35_35_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /shares/zitipoolhome/ol233/mb-fpga-VU9P/MandelbulbVU9P/MandelbulbVU9P.gen/sources_1/ip/mult_35_35_core/mult_35_35_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_35_35_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
