set_property SRC_FILE_INFO {cfile:/shares/zitipoolhome/ol233/mb-fpga-VU9P/MandelbulbVU9P/MandelbulbVU9P.srcs/constrs_1/new/board_constr.xdc rfile:../../../MandelbulbVU9P.srcs/constrs_1/new/board_constr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G31  IOSTANDARD DIFF_SSTL12} [get_ports clk_300mhz_p]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F31  IOSTANDARD DIFF_SSTL12} [get_ports clk_300mhz_n]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN BB24 IOSTANDARD LVCMOS18} [get_ports btnu]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN BF22 IOSTANDARD LVCMOS18} [get_ports btnl]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN BE22 IOSTANDARD LVCMOS18} [get_ports btnd]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN BE23 IOSTANDARD LVCMOS18} [get_ports btnr]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN BD23 IOSTANDARD LVCMOS18} [get_ports btnc]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B17  IOSTANDARD LVCMOS12} [get_ports {sw0}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G16  IOSTANDARD LVCMOS12} [get_ports {sw1}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AY14 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {o_pix_clk}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AY15 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {o_pix_clk_5x}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AW15 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {TMDS_shift_red0}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AV15 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {TMDS_shift_red1}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AV16 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {TMDS_shift_green0}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AU16 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {TMDS_shift_green1}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AT15 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {TMDS_shift_blue0}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AT16 IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 8} [get_ports {TMDS_shift_blue1}]
